_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
classification_report_path:
    value: artifacts\model_validation\classification_report.txt
confusion_matrix_path:
    value: artifacts\model_validation\confusion_matrix.png
model_path:
    value: artifacts\model_trainer\leads_score.joblib
optimal_threshold:
    value: 0.3
pr_curve_path:
    value: artifacts\model_validation\pr_curve.png
precision_recall_path:
    value: artifacts\model_validation\precision_recall.png
project_name:
    value: leads-scoring
roc_curve_path:
    value: artifacts\model_validation\roc_curve.png
root_dir:
    value: artifacts\model_validation
test_feature_path:
    value: artifacts\data_transformation\X_test_transformed.joblib
test_targets_path:
    value: artifacts\data_transformation\y_test.csv
validation_scores_path:
    value: artifacts\model_validation\model_val_scores.json
